import React, { useEffect, useState } from 'react';
import { API_BASE } from '../../api/config';
import { useToast } from '../../components/Toast/useToast';
import { ToastContainer } from '../../components/Toast/Toast';

export default function AtencionesExternas() {
  const [mascotas, setMascotas] = useState([]); const [expediente, setExpediente] = useState(null);
  const [atenciones, setAtenciones] = useState([]); const [mascotaId, setMascotaId] = useState('');
  const [form, setForm] = useState({ nombreVeterinaria: '', nombreProfesional: '', fechaAtencion: '', motivo: '', diagnostico: '', tratamiento: '' });
  const { toasts, showToast, removeToast } = useToast();
  const token = () => localStorage.getItem('token_huellitas');
  useEffect(() => { fetch(`${API_BASE}/usuario/mascotas`, { headers: { Authorization: `Bearer ${token()}` } }).then(r => r.json()).then(d => setMascotas(d.mascotas || [])).catch(() => showToast('No se pudieron cargar las mascotas.', 'error')); }, []);
  const seleccionar = async (id) => { setMascotaId(id); setExpediente(null); setAtenciones([]); const r = await fetch(`${API_BASE}/expediente/mascota/${id}`, { headers: { Authorization: `Bearer ${token()}` } }); const d = await r.json(); if (!r.ok) return showToast(d.mensaje, 'warning'); setExpediente(d.expediente); const a = await fetch(`${API_BASE}/expedientes/${d.expediente.idExpediente}/atenciones-externas`, { headers: { Authorization: `Bearer ${token()}` } }); const ad = await a.json(); setAtenciones(ad.atenciones || []); };
  const guardar = async (e) => { e.preventDefault(); if (!expediente) return showToast('Selecciona una mascota con expediente.', 'warning'); const r = await fetch(`${API_BASE}/expedientes/${expediente.idExpediente}/atenciones-externas`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}` }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) return showToast(d.mensaje || 'No se pudo registrar.', 'error'); showToast('Atención externa registrada.', 'success'); seleccionar(mascotaId); };
  return <main className="main-content" style={{ padding: 32 }}><h1>Atenciones externas</h1><p>Registra consultas realizadas fuera de Huellitas Vitales.</p><select value={mascotaId} onChange={e => seleccionar(e.target.value)}><option value="">Selecciona una mascota</option>{mascotas.map(m => <option key={m.idMascota} value={m.idMascota}>{m.nombre}</option>)}</select>{expediente && <><form onSubmit={guardar} style={{ display: 'grid', gap: 10, maxWidth: 650, marginTop: 24 }}><input required placeholder="Veterinaria o establecimiento" onChange={e => setForm({...form, nombreVeterinaria:e.target.value})}/><input placeholder="Profesional" onChange={e => setForm({...form, nombreProfesional:e.target.value})}/><input required type="datetime-local" onChange={e => setForm({...form, fechaAtencion:e.target.value})}/><textarea required placeholder="Motivo" onChange={e => setForm({...form, motivo:e.target.value})}/><textarea placeholder="Diagnóstico" onChange={e => setForm({...form, diagnostico:e.target.value})}/><textarea placeholder="Tratamiento" onChange={e => setForm({...form, tratamiento:e.target.value})}/><button className="btn-main">Registrar atención</button></form><h2 style={{marginTop:32}}>Historial externo</h2>{atenciones.map(a => <article className="content-card" key={a.idAtencionExterna}><strong>{a.nombreVeterinaria}</strong><p>{a.motivo}</p><p>{a.diagnostico || 'Sin diagnóstico registrado'}</p></article>)}</>}<ToastContainer toasts={toasts} removeToast={removeToast}/></main>;
}
