### 1. LOGIN (Ejecuta esto y copia el token que sale a la derecha)
POST http://localhost:5010/api/Login/local
Content-Type: application/json

{
  "correo": "eduaba8@gmail.com",
  "password": "1234"
}

### ------------------------------------------

### 2. ACTUALIZAR PERFIL (Pega tu token limpio después de Bearer)
PUT http://localhost:5010/api/Usuario/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJlZHVhYmE4QGdtYWlsLmNvbSIsInJvbCI6IjMiLCJleHAiOjE3ODU2Mjk3NTV9.KadgLhzXPJcm6AEOdXem8g7g1CXhT27D5gon7kZz0jQ
Content-Type: application/json

{
  "nombre": "Javier Antonio",
  "apellidos": "Powers Abarca",
  "correo": "eduaba8@gmail.com",
  "telefono": "88888888"
}