<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\bootstrap\css\**" />
    <Compile Remove="wwwroot\lib\bootstrap\js\**" />
    <Compile Remove="wwwroot\lib\bootstrap\scss\**" />
    <Content Remove="wwwroot\lib\bootstrap\css\**" />
    <Content Remove="wwwroot\lib\bootstrap\js\**" />
    <Content Remove="wwwroot\lib\bootstrap\scss\**" />
    <EmbeddedResource Remove="wwwroot\lib\bootstrap\css\**" />
    <EmbeddedResource Remove="wwwroot\lib\bootstrap\js\**" />
    <EmbeddedResource Remove="wwwroot\lib\bootstrap\scss\**" />
    <None Remove="wwwroot\lib\bootstrap\css\**" />
    <None Remove="wwwroot\lib\bootstrap\js\**" />
    <None Remove="wwwroot\lib\bootstrap\scss\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Components\" />
    <Folder Include="wwwroot\lib\bootstrap\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Views\Login\Index.html" />
    <None Include="wwwroot\Views\Login\login.html" />
    <None Include="wwwroot\Views\Login\register.html" />
  </ItemGroup>

</Project>