// <auto-generated />
using System;
using HuellitasVitalesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuellasVitalesAPI.Migrations
{
    [DbContext(typeof(ConexionDB))]
    [Migration("20260804015954_AgregarServicioVeterinario")]
    partial class AgregarServicioVeterinario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.Comercio", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComercio"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_RESOLUCION");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_SOLICITUD");

                    b.Property<byte>("IdEstadoSolicitud")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdPersonaLegal")
                        .HasColumnType("int");

                    b.Property<byte>("IdTipoComercio")
                        .HasColumnType("tinyint");

                    b.Property<int?>("IdUsuarioResolvio")
                        .HasColumnType("int")
                        .HasColumnName("IDUSUARIO_RESOLVIO");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE_COMERCIAL");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComercio");

                    b.ToTable("COMERCIO", (string)null);
                });

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.PersonaLegal", b =>
                {
                    b.Property<int>("IdPersonaLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonaLegal"));

                    b.Property<byte>("IdTipoPersona")
                        .HasColumnType("tinyint");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RAZON_SOCIAL");

                    b.HasKey("IdPersonaLegal");

                    b.ToTable("PERSONA_LEGAL", (string)null);
                });

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IdEstadoCuenta")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IdRol")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor_Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.Veterinario", b =>
                {
                    b.Property<int>("IdVeterinario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeterinario"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdVeterinario");

                    b.ToTable("VETERINARIO", (string)null);
                });

            modelBuilder.Entity("HuellasVitalesAPI.Backend.Models.Entidades.VeterinaryService", b =>
                {
                    b.Property<int>("IdServicioVeterinario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicioVeterinario"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("DURACION_MINUTOS");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NOMBRE");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRECIO");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.HasKey("IdServicioVeterinario");

                    b.ToTable("SERVICIO_VETERINARIO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
